language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t visheshmadaan13/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true visheshmadaan13/react-test npm test -- --coverage
after_success:
  - docker build -t visheshmadaan13/multi-client ./client
  - docker build -t visheshmadaan13/multi-server ./server
  - docker build -t visheshmadaan13/multi-nginx ./nginx
  - docker build -t visheshmadaan13/multi-worker ./worker
  # log in to the docker CLI
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_ID" --password-stdin
  # take these images and push them to dockerhub
  - docker push visheshmadaan13/multi-client
  - docker push visheshmadaan13/multi-server
  - docker push visheshmadaan13/multi-nginx
  - docker push visheshmadaan13/multi-worker
  
